import os
import smtplib
import pathlib
import sys
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email.encoders import encode_base64

def send_report_email(recipient_email, sender_email=None, sender_password=None, smtp_server="smtp.gmail.com", smtp_port=587):
    """
    Sends the generated PDF and PPTX analytics reports to the target investor or AMC manager.
    If credentials are not found, mocks the delivery to allow offline local testing.
    """
    print(f"\n--- Initiating Email Automation Job ---")
    print(f"Target Recipient: {recipient_email}")
    
    # Path configuration
    base_dir = pathlib.Path(__file__).resolve().parent.parent
    pdf_path = base_dir / "reports" / "Final_Report.pdf"
    pptx_path = base_dir / "reports" / "Presentation.pptx"
    
    # Verify attachments exist
    if not pdf_path.exists() or not pptx_path.exists():
        print("Error: Report attachments not found. Running report generator first...")
        try:
            # Dynamically run report generator
            from generate_reports import create_pdf_report, create_pptx_presentation
            create_pdf_report()
            create_pptx_presentation()
        except ImportError:
            print("Error: Could not import generate_reports. Make sure scripts are in path.")
            return False
            
    # Setup sender details
    sender_email = sender_email or os.environ.get("BLUESTOCK_SMTP_SENDER")
    sender_password = sender_password or os.environ.get("BLUESTOCK_SMTP_PASSWORD")
    
    # Message Construction
    msg = MIMEMultipart()
    msg['From'] = sender_email if sender_email else "analytics@bluestockfintech.com"
    msg['To'] = recipient_email
    msg['Subject'] = "📊 Bluestock Capstone - Mutual Fund Performance Analytics Executive Reports"
    
    body = """Dear Team / Investor,

Please find attached the automated executive reports generated by the Bluestock Mutual Fund Analytics Platform.

Included Deliverables:
1. Final_Report.pdf - Performance attributions (Sharpe, Sortino, Alpha, Beta, VaR) and Star Schema schema definitions.
2. Presentation.pptx - Executive slide deck summarizing the Capstone pipeline, models, and findings.

This email is automatically generated by the Bluestock scheduled analytics engine.

Best Regards,
Bluestock Fintech Data Engineering & Analytics Division
"""
    msg.attach(MIMEText(body, 'plain'))
    
    # Attach PDF
    try:
        with open(pdf_path, "rb") as f:
            part = MIMEBase('application', 'octet-stream')
            part.set_payload(f.read())
            encode_base64(part)
            part.add_header('Content-Disposition', f'attachment; filename="{pdf_path.name}"')
            msg.attach(part)
        print(f"Successfully attached PDF: {pdf_path.name}")
    except Exception as e:
        print(f"Warning: Failed to attach PDF: {e}")
        
    # Attach PPTX
    try:
        with open(pptx_path, "rb") as f:
            part = MIMEBase('application', 'octet-stream')
            part.set_payload(f.read())
            encode_base64(part)
            part.add_header('Content-Disposition', f'attachment; filename="{pptx_path.name}"')
            msg.attach(part)
        print(f"Successfully attached PPTX: {pptx_path.name}")
    except Exception as e:
        print(f"Warning: Failed to attach PPTX: {e}")
        
    # Check if credentials are present, otherwise run in Mock/Dry-run mode
    if not sender_email or not sender_password:
        print("\n[MOCK MODE ACTIVE]: SMTP credentials not set (BLUESTOCK_SMTP_SENDER/PASSWORD env variables missing).")
        print("Writing email delivery log to local mock file for validation...")
        
        mock_log_path = base_dir / "reports" / "email_delivery_mock.log"
        with open(mock_log_path, "w", encoding="utf-8") as f:
            f.write(f"Timestamp: {os.popen('date /t').read().strip()} {os.popen('time /t').read().strip()}\n")
            f.write(f"From: {msg['From']}\n")
            f.write(f"To: {msg['To']}\n")
            f.write(f"Subject: {msg['Subject']}\n")
            f.write("-" * 50 + "\n")
            f.write(body)
            f.write("-" * 50 + "\n")
            f.write(f"Attachments: {pdf_path.name}, {pptx_path.name}\n")
            f.write("Status: MOCK_DELIVERED_SUCCESSFULLY\n")
            
        print(f"Mock email delivery log saved to: {mock_log_path.resolve()}")
        print("EMAIL AUTOMATION VERIFIED (DRY RUN SUCCEEDED).")
        return True
        
    # Real SMTP Sending
    try:
        print(f"Connecting to SMTP server {smtp_server}:{smtp_port}...")
        server = smtplib.SMTP(smtp_server, smtp_port)
        server.starttls()
        server.login(sender_email, sender_password)
        server.send_message(msg)
        server.quit()
        print("REAL EMAIL SENT SUCCESSFULLY!")
        return True
    except Exception as e:
        print(f"SMTP Error encountered during sending: {str(e)}")
        print("Falling back to local mock logging.")
        return False

if __name__ == "__main__":
    test_recipient = "investor@example.com"
    if len(sys.argv) > 1:
        test_recipient = sys.argv[1]
    send_report_email(test_recipient)
